#!/bin/sh

#Repository name : basement
DEPLOY_DIR="$(dirname "$PWD")/basement/instance"
PID_FILE="${DEPLOY_DIR}/pid.log"
LOG_FILE="${DEPLOY_DIR}/app.log"

unset GIT_DIR

if [ ! -d "${DEPLOY_DIR}" ]; then
    echo "Deployment directory ${DEPLOY_DIR} does not exist. Creating."
    mkdir -p "${DEPLOY_DIR}"
fi

git --work-tree=${DEPLOY_DIR} checkout -f

echo "Code checked out to: ${DEPLOY_DIR}"

cd "${DEPLOY_DIR}" || exit
chmod u+x dev_run.sh
chmod u+x mvnw

if [ -f "${PID_FILE}" ]; then
    OLD_PID=$(cat "${PID_FILE}")
    echo "Stopping old process (PID: ${OLD_PID})..."
    kill -9 "${OLD_PID}" 2>/dev/null
    rm -f "${PID_FILE}"
fi

echo "Starting application with nohup"

nohup ./dev_run.sh > "${LOG_FILE}" 2>&1 &
# $! 变量捕获上一个后台命令（&）的 PID
NEW_PID=$!

echo "${NEW_PID}" > "${PID_FILE}"

echo "New process started (PID: ${NEW_PID}). PID recorded to ${PID_FILE}"
echo "Deployment completed."