#!/bin/sh

#Repository name : basement
DEPLOY_DIR="$(dirname "$PWD")/basement/instance"
LOG_FILE="${DEPLOY_DIR}/app.log"

unset GIT_DIR

if [ ! -d "${DEPLOY_DIR}" ]; then
    echo "Deployment directory ${DEPLOY_DIR} does not exist. Creating."
    mkdir -p "${DEPLOY_DIR}"
fi

git --work-tree=${DEPLOY_DIR} checkout -f

echo "Code checked out to: ${DEPLOY_DIR}"

cd "${DEPLOY_DIR}" || exit
chmod u+x dev_run.sh
chmod u+x mvnw

echo "Starting application with nohup"

nohup ./dev_run.sh > "${LOG_FILE}" 2>&1 &

echo "Deployment completed."